name: Pull iCloud Private Relay IP Ranges

on:
  workflow_dispatch:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  pull-external-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create directory if not exists
        run: mkdir -p ExternalData
      
      - name: Download and save iCloud Private Relay IP Ranges
        run: |
          echo "Downloading iCloud Private Relay IP ranges..."
          curl -s "https://mask-api.icloud.com/egress-ip-ranges.csv" > ExternalData/iCloudPrivateRelayIPRanges.csv
          
          # Verify file was downloaded and has content
          if [ ! -s ExternalData/iCloudPrivateRelayIPRanges.csv ]; then
            echo "Error: Downloaded file is empty or doesn't exist"
            exit 1
          fi
          
          # Count lines for logging
          lines=$(wc -l < ExternalData/iCloudPrivateRelayIPRanges.csv)
          echo "Downloaded $lines IP ranges"
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update iCloud Private Relay IP ranges - $(date -u +%Y-%m-%d)"
          file_pattern: 'ExternalData/iCloudPrivateRelayIPRanges.csv'
          commit_user_name: 'iCloud Relay Data Updater'
          commit_user_email: 'actions@github.com'
          push_options: '--force-with-lease'
